title: Whisper of Koori
description: 一个用来絮絮叨叨的地方，话题包含动漫、图书、电影、追星，能力允许会记录专业上的小科普

url: http://SadieKoori.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: 小书匠
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Sadie's corner
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: SadieKoori
  twitter: Sadie_こおり
  weibo: Sadie_土撥鼠_koori
  instagram: Sadieee51
  email: stageta2tuboshu@gmail.com

google_analytics: "UA-58263416-1"
